"""requirements.txt is a generated lock of pyproject.toml, not a source file.

Docker, CI and the README all `pip install -r requirements.txt`, so the
lock is what actually ships. Two things keep it honest: CI's lock-check
step regenerates it and diffs (catches a stale lock), and these tests
catch the cheaper mistakes that a diff cannot express — a hand-edited
file that lost its header, or a dependency added to pyproject.toml whose
lock was regenerated by an older tool that silently dropped it.
"""
from __future__ import annotations

import pathlib
import re
import tomllib

BACKEND = pathlib.Path(__file__).resolve().parents[2]
PYPROJECT = BACKEND / "pyproject.toml"
LOCK = BACKEND / "requirements.txt"

# PEP 508: the distribution name is everything before the first extras
# bracket, version operator, marker or whitespace.
_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def _normalize(name: str) -> str:
    """PEP 503 normalisation, which is how uv writes names into the lock."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _declared_dependency_names() -> list[str]:
    with PYPROJECT.open("rb") as fh:
        project = tomllib.load(fh)["project"]
    assert "dependencies" in project, "pyproject.toml must declare [project.dependencies]"
    assert "dependencies" not in project.get("dynamic", []), (
        "dependencies must be static in pyproject.toml, not read back from requirements.txt"
    )
    names = []
    for spec in project["dependencies"]:
        match = _NAME_RE.match(spec)
        assert match, f"unparseable requirement: {spec!r}"
        names.append(_normalize(match.group(1)))
    return names


def _pinned_names() -> set[str]:
    pinned = set()
    for line in LOCK.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # uv writes `name==version` and, for extras, `name[extra]==version`.
        match = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?==\S+", line)
        assert match, f"requirements.txt is not fully pinned: {line!r}"
        pinned.add(_normalize(match.group(1)))
    return pinned


def test_lock_carries_the_generated_header():
    """The first line is the marker a reviewer sees before editing by hand,
    and the comment block under it must say where to edit instead."""
    lines = LOCK.read_text().splitlines()
    assert lines[0].startswith("# GENERATED"), (
        f"requirements.txt first line is {lines[0]!r}; regenerate it with `make lock`"
    )
    header = "\n".join(line for line in lines[:10] if line.startswith("#"))
    assert "pyproject.toml" in header and "make lock" in header


def test_every_declared_dependency_is_pinned_in_the_lock():
    declared = _declared_dependency_names()
    assert declared, "pyproject.toml declares no dependencies"
    missing = sorted(set(declared) - _pinned_names())
    assert not missing, (
        f"declared in pyproject.toml but absent from requirements.txt: {missing}; "
        "run `make lock` from backend/"
    )


def test_lock_has_no_unpinned_lines():
    """`_pinned_names` asserts per line; calling it is the whole test."""
    assert _pinned_names()
