"""Wave 7A — discretionary research notes injection.

User-curated investment notes (book excerpts, PM interviews, articles,
personal frameworks) live under `research_notes/` and get filtered into
the relevant agent prompts via tag-based routing. This solves the
"I read something interesting and want the agents to know" problem
without muddying context as the corpus grows.

Folder layout:
    research_notes/
    ├── _index.json                  # auto-generated by the indexer
    ├── books/
    │   └── pat-dorsey-moats.md
    ├── interviews/
    ├── articles/
    ├── frameworks/
    └── personal/

Each note has a YAML frontmatter block declaring routing
(`applies_to_agents`, `applies_to_sectors`, `applies_to_tickers`,
`applies_to_sub_industries`) + lifecycle (`weight`, `expires`,
`status`). The body is free-form markdown.

This module exposes:
- `ResearchNote` / `NoteFrontmatter` Pydantic schemas.
- `parse_note(path)` — read + parse a single .md file with frontmatter.
- `list_notes(corpus_root)` — scan the corpus, return all parsed notes.
- `select_for(agent, sector, ...)` — filter the corpus to a relevant
  subset, sorted by `weight`. Returns `NoteSummary` (summaries only,
  not bodies; bodies are reserved for Wave 7B).
- `render_summary_block(notes)` — produce the markdown block injected
  into the agent prompt.

Routing semantics:
- `applies_to_agents = []` → applies to no agents (effectively dormant).
- `applies_to_sectors = ["*"]` → applies to every sector.
- A note matches when EVERY supplied filter overlaps the note's tags
  OR the note's tag for that dimension is `["*"]`. A `personal`-folder
  note with `applies_to_tickers = ["NVDA"]` matches only NVDA memos.
- Expired notes (`expires` < today) AND non-active status notes are dropped.
"""
from __future__ import annotations

import json
import logging
import re
from datetime import date as _date
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

log = logging.getLogger(__name__)


# Frontmatter delimiter: standard YAML --- ... ---
_FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.DOTALL)


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class NoteFrontmatter(BaseModel):
    """Tagged metadata for a research note. Defaults match the
    "least-restrictive" routing so a minimally-tagged note still surfaces
    somewhere obvious (sector agent, all sectors, weight 0.5)."""
    title: str
    source: str = ""
    date: Optional[str] = None  # YYYY-MM-DD
    applies_to_agents: List[str] = Field(default_factory=lambda: ["sector"])
    applies_to_sectors: List[str] = Field(default_factory=lambda: ["*"])
    applies_to_sub_industries: List[str] = Field(default_factory=list)
    applies_to_tickers: List[str] = Field(default_factory=list)
    weight: float = 0.5
    expires: Optional[str] = None  # YYYY-MM-DD
    status: str = "active"  # active | archived | superseded
    chars: int = 0
    summary: str = ""


class ResearchNote(BaseModel):
    """A parsed note: frontmatter + markdown body."""
    path: str
    frontmatter: NoteFrontmatter
    body: str


class NoteSummary(BaseModel):
    """The compact projection injected into agent prompts.

    Doesn't carry the body — that's a Wave 7B concern (BM25 over body
    text for top-K relevance). Summary-only injection caps the per-run
    context budget at ~30 tokens × number of matches.
    """
    title: str
    source: str = ""
    summary: str = ""
    weight: float = 0.5
    applies_to_agents: List[str] = Field(default_factory=list)
    applies_to_sectors: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Parsing + corpus walk
# ---------------------------------------------------------------------------

def _root_default() -> Path:
    """Default corpus root: <repo>/research_notes/. Anchored to the
    backend directory so callers in any CWD see the same files."""
    backend_root = Path(__file__).resolve().parent.parent.parent
    repo_root = backend_root.parent
    return repo_root / "research_notes"


def _parse_frontmatter(text: str) -> tuple[Dict[str, Any], str]:
    """Split a markdown file into `(frontmatter_dict, body)`.

    Returns `({}, full_text)` when no frontmatter delimiter is found —
    bodies-only notes are still indexed (with default frontmatter).
    """
    m = _FM_RE.match(text or "")
    if not m:
        return {}, text or ""
    fm_block, body = m.group(1), m.group(2)
    try:
        import yaml
        data = yaml.safe_load(fm_block) or {}
    except Exception as exc:  # pragma: no cover — defensive
        log.warning("YAML parse failed: %s", exc)
        return {}, body
    if not isinstance(data, dict):
        return {}, body
    return data, body


def parse_note(path: Path) -> Optional[ResearchNote]:
    """Read + parse one .md file. Returns None on read failure."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception as exc:
        log.warning("research-notes parse failed for %s: %s", path, exc)
        return None
    fm_data, body = _parse_frontmatter(text)
    fm_data = dict(fm_data)
    # Default `title` to the filename stem when missing — mandatory field.
    fm_data.setdefault("title", path.stem)
    fm_data.setdefault("chars", len(body))
    fm_data.setdefault("summary", _deterministic_summary(body))
    try:
        fm = NoteFrontmatter(**fm_data)
    except Exception as exc:
        log.warning("research-note frontmatter invalid at %s: %s", path, exc)
        return None
    return ResearchNote(path=str(path), frontmatter=fm, body=body)


def _deterministic_summary(body: str, max_chars: int = 200) -> str:
    """First-paragraph extract for notes without an explicit summary.

    Live mode would use an LLM via the indexer; the deterministic
    fallback runs at parse time so notes always have *some* summary.
    """
    if not body:
        return ""
    # Drop initial markdown headings.
    lines = []
    for ln in body.splitlines():
        s = ln.strip()
        if not s:
            if lines:
                break
            continue
        if s.startswith("#"):
            continue
        lines.append(s)
    para = " ".join(lines)
    if len(para) > max_chars:
        para = para[:max_chars].rstrip() + "…"
    return para


def list_notes(corpus_root: Optional[Path] = None) -> List[ResearchNote]:
    """Walk the corpus, return all parseable notes.

    Recurses into subfolders. Files not ending in `.md` are skipped.
    """
    root = Path(corpus_root) if corpus_root else _root_default()
    if not root.exists():
        return []
    out: List[ResearchNote] = []
    for path in sorted(root.rglob("*.md")):
        note = parse_note(path)
        if note is not None:
            out.append(note)
    return out


# ---------------------------------------------------------------------------
# Filtering / selection
# ---------------------------------------------------------------------------

def _matches_filter(note_tags: List[str], target: Optional[str]) -> bool:
    """Tag-list match with wildcard support.

    - target is None → no filter on this dimension (always matches).
    - note_tags == [] → note doesn't apply to this dimension.
    - note_tags contains "*" → note applies to everything.
    - else: case-insensitive equality match on `target` against any tag.
    """
    if target is None:
        return True
    if not note_tags:
        return False
    if "*" in note_tags:
        return True
    target_norm = (target or "").strip().lower()
    return any(str(t).strip().lower() == target_norm for t in note_tags)


def _is_active(fm: NoteFrontmatter, today: Optional[_date] = None) -> bool:
    if fm.status != "active":
        return False
    if not fm.expires:
        return True
    today = today or _date.today()
    try:
        exp = _date.fromisoformat(str(fm.expires)[:10])
    except (TypeError, ValueError):
        return True  # malformed expiry → treat as no expiry rather than drop
    return exp >= today


def select_for(
    agent_name: str, *,
    sector: Optional[str] = None,
    sub_industry: Optional[str] = None,
    ticker: Optional[str] = None,
    corpus_root: Optional[Path] = None,
    max_notes: int = 6,
    today: Optional[_date] = None,
) -> List[NoteSummary]:
    """Filter the corpus to notes relevant to this run, sorted by weight.

    Filter dimensions cascade — every supplied dimension must match.
    Weight ordering is descending (heavier first); ties broken by title
    alphabetically for determinism.
    """
    notes = list_notes(corpus_root=corpus_root)
    out: List[NoteSummary] = []
    for n in notes:
        fm = n.frontmatter
        if not _is_active(fm, today=today):
            continue
        if not _matches_filter(fm.applies_to_agents, agent_name):
            continue
        if not _matches_filter(fm.applies_to_sectors, sector):
            continue
        if not _matches_filter(fm.applies_to_sub_industries, sub_industry):
            continue
        if not _matches_filter(fm.applies_to_tickers, ticker):
            continue
        out.append(NoteSummary(
            title=fm.title, source=fm.source, summary=fm.summary,
            weight=fm.weight,
            applies_to_agents=fm.applies_to_agents,
            applies_to_sectors=fm.applies_to_sectors,
        ))
    out.sort(key=lambda s: (-s.weight, s.title.lower()))
    return out[:max_notes]


def render_summary_block(notes: List[NoteSummary]) -> str:
    """Render a markdown block to splice into an agent prompt.

    Returns the empty string when `notes` is empty so callers can
    unconditionally concatenate the result.
    """
    if not notes:
        return ""
    lines = ["## Discretionary investment context"]
    for n in notes:
        src = f" ({n.source})" if n.source else ""
        summary = n.summary or "—"
        lines.append(f"- **{n.title}**{src}: {summary}")
    return "\n".join(lines)
