"""Wave 7A — discretionary research notes injection.

User-curated investment notes (book excerpts, PM interviews, articles,
personal frameworks) live under `research_notes/` and get filtered into
the relevant agent prompts via tag-based routing. This solves the
"I read something interesting and want the agents to know" problem
without muddying context as the corpus grows.

Folder layout:
    research_notes/
    ├── _index.json                  # auto-generated by the indexer
    ├── books/
    │   └── pat-dorsey-moats.md
    ├── interviews/
    ├── articles/
    ├── frameworks/
    └── personal/

Each note has a YAML frontmatter block declaring routing
(`applies_to_agents`, `applies_to_sectors`, `applies_to_tickers`,
`applies_to_sub_industries`) + lifecycle (`weight`, `expires`,
`status`). The body is free-form markdown.

This module exposes:
- `ResearchNote` / `NoteFrontmatter` Pydantic schemas.
- `parse_note(path)` — read + parse a single .md file with frontmatter.
- `list_notes(corpus_root)` — scan the corpus, return all parsed notes.
- `select_for(agent, sector, ...)` — filter the corpus to a relevant
  subset, sorted by `weight`. Returns `NoteSummary` (summaries only,
  not bodies; bodies are reserved for Wave 7B).
- `render_summary_block(notes)` — produce the markdown block injected
  into the agent prompt.

Routing semantics:
- `applies_to_agents = []` → applies to no agents (effectively dormant).
- `applies_to_sectors = ["*"]` → applies to every sector.
- A note matches when EVERY supplied filter overlaps the note's tags
  OR the note's tag for that dimension is `["*"]`. A `personal`-folder
  note with `applies_to_tickers = ["NVDA"]` matches only NVDA memos.
- Expired notes (`expires` < today) AND non-active status notes are dropped.
"""
from __future__ import annotations

import json
import logging
import re
from datetime import date as _date
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

log = logging.getLogger(__name__)


# Frontmatter delimiter: standard YAML --- ... ---
_FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.DOTALL)


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class NoteFrontmatter(BaseModel):
    """Tagged metadata for a research note. Defaults match the
    "least-restrictive" routing so a minimally-tagged note still surfaces
    somewhere obvious (sector agent, all sectors, weight 0.5)."""
    title: str
    source: str = ""
    date: Optional[str] = None  # YYYY-MM-DD
    applies_to_agents: List[str] = Field(default_factory=lambda: ["sector"])
    applies_to_sectors: List[str] = Field(default_factory=lambda: ["*"])
    applies_to_sub_industries: List[str] = Field(default_factory=list)
    applies_to_tickers: List[str] = Field(default_factory=list)
    weight: float = 0.5
    expires: Optional[str] = None  # YYYY-MM-DD
    status: str = "active"  # active | archived | superseded
    chars: int = 0
    summary: str = ""


class ResearchNote(BaseModel):
    """A parsed note: frontmatter + markdown body."""
    path: str
    frontmatter: NoteFrontmatter
    body: str


class NoteSummary(BaseModel):
    """The compact projection injected into agent prompts.

    Doesn't carry the body — that's a Wave 7B concern (BM25 over body
    text for top-K relevance). Summary-only injection caps the per-run
    context budget at ~30 tokens × number of matches.
    """
    title: str
    source: str = ""
    summary: str = ""
    weight: float = 0.5
    applies_to_agents: List[str] = Field(default_factory=list)
    applies_to_sectors: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Parsing + corpus walk
# ---------------------------------------------------------------------------

def _root_default() -> Path:
    """Default corpus root: <repo>/research_notes/. Anchored to the
    backend directory so callers in any CWD see the same files."""
    backend_root = Path(__file__).resolve().parent.parent.parent
    repo_root = backend_root.parent
    return repo_root / "research_notes"


def _parse_frontmatter(text: str) -> tuple[Dict[str, Any], str]:
    """Split a markdown file into `(frontmatter_dict, body)`.

    Returns `({}, full_text)` when no frontmatter delimiter is found —
    bodies-only notes are still indexed (with default frontmatter).
    """
    m = _FM_RE.match(text or "")
    if not m:
        return {}, text or ""
    fm_block, body = m.group(1), m.group(2)
    try:
        import yaml
        data = yaml.safe_load(fm_block) or {}
    except Exception as exc:  # pragma: no cover — defensive
        log.warning("YAML parse failed: %s", exc)
        return {}, body
    if not isinstance(data, dict):
        return {}, body
    return data, body


def parse_note(path: Path) -> Optional[ResearchNote]:
    """Read + parse one .md file. Returns None on read failure."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception as exc:
        log.warning("research-notes parse failed for %s: %s", path, exc)
        return None
    fm_data, body = _parse_frontmatter(text)
    fm_data = dict(fm_data)
    # Default `title` to the filename stem when missing — mandatory field.
    fm_data.setdefault("title", path.stem)
    fm_data.setdefault("chars", len(body))
    fm_data.setdefault("summary", _deterministic_summary(body))
    try:
        fm = NoteFrontmatter(**fm_data)
    except Exception as exc:
        log.warning("research-note frontmatter invalid at %s: %s", path, exc)
        return None
    return ResearchNote(path=str(path), frontmatter=fm, body=body)


def _deterministic_summary(body: str, max_chars: int = 200) -> str:
    """First-paragraph extract for notes without an explicit summary.

    Live mode would use an LLM via the indexer; the deterministic
    fallback runs at parse time so notes always have *some* summary.
    """
    if not body:
        return ""
    # Drop initial markdown headings.
    lines = []
    for ln in body.splitlines():
        s = ln.strip()
        if not s:
            if lines:
                break
            continue
        if s.startswith("#"):
            continue
        lines.append(s)
    para = " ".join(lines)
    if len(para) > max_chars:
        para = para[:max_chars].rstrip() + "…"
    return para


def list_notes(corpus_root: Optional[Path] = None) -> List[ResearchNote]:
    """Walk the corpus, return all parseable notes.

    Recurses into subfolders. Files not ending in `.md` are skipped.
    """
    root = Path(corpus_root) if corpus_root else _root_default()
    if not root.exists():
        return []
    out: List[ResearchNote] = []
    for path in sorted(root.rglob("*.md")):
        note = parse_note(path)
        if note is not None:
            out.append(note)
    return out


# ---------------------------------------------------------------------------
# Filtering / selection
# ---------------------------------------------------------------------------

def _matches_filter(
    note_tags: List[str], target: Optional[str],
    *, empty_means_no_restriction: bool = False,
) -> bool:
    """Tag-list match with wildcard support.

    - target is None → no filter on this dimension (always matches).
    - note_tags contains "*" → applies to everything.
    - note_tags == [] →
        * by default: dormant (note doesn't apply to this dimension).
          Used for `applies_to_agents` and `applies_to_sectors` where
          the *non-empty* default is the source of truth.
        * with `empty_means_no_restriction=True`: applies to anything.
          Used for `applies_to_sub_industries` and `applies_to_tickers`
          where the default is `[]` and emptiness encodes "no narrowing".
    - else: case-insensitive equality match on `target` against any tag.
    """
    if target is None:
        return True
    if not note_tags:
        return empty_means_no_restriction
    if "*" in note_tags:
        return True
    target_norm = (target or "").strip().lower()
    return any(str(t).strip().lower() == target_norm for t in note_tags)


def _is_active(fm: NoteFrontmatter, today: Optional[_date] = None) -> bool:
    if fm.status != "active":
        return False
    if not fm.expires:
        return True
    today = today or _date.today()
    try:
        exp = _date.fromisoformat(str(fm.expires)[:10])
    except (TypeError, ValueError):
        return True  # malformed expiry → treat as no expiry rather than drop
    return exp >= today


def select_for(
    agent_name: str, *,
    sector: Optional[str] = None,
    sub_industry: Optional[str] = None,
    ticker: Optional[str] = None,
    corpus_root: Optional[Path] = None,
    max_notes: int = 6,
    today: Optional[_date] = None,
) -> List[NoteSummary]:
    """Filter the corpus to notes relevant to this run, sorted by weight.

    Filter dimensions cascade — every supplied dimension must match.
    Weight ordering is descending (heavier first); ties broken by title
    alphabetically for determinism.
    """
    notes = list_notes(corpus_root=corpus_root)
    out: List[NoteSummary] = []
    for n in notes:
        fm = n.frontmatter
        if not _is_active(fm, today=today):
            continue
        if not _matches_filter(fm.applies_to_agents, agent_name):
            continue
        if not _matches_filter(fm.applies_to_sectors, sector):
            continue
        # Sub-industry / ticker have empty defaults, so empty = "no narrowing".
        if not _matches_filter(
            fm.applies_to_sub_industries, sub_industry,
            empty_means_no_restriction=True,
        ):
            continue
        if not _matches_filter(
            fm.applies_to_tickers, ticker,
            empty_means_no_restriction=True,
        ):
            continue
        out.append(NoteSummary(
            title=fm.title, source=fm.source, summary=fm.summary,
            weight=fm.weight,
            applies_to_agents=fm.applies_to_agents,
            applies_to_sectors=fm.applies_to_sectors,
        ))
    out.sort(key=lambda s: (-s.weight, s.title.lower()))
    return out[:max_notes]


def render_summary_block(notes: List[NoteSummary]) -> str:
    """Render a markdown block to splice into an agent prompt.

    Returns the empty string when `notes` is empty so callers can
    unconditionally concatenate the result.
    """
    if not notes:
        return ""
    lines = ["## Discretionary investment context"]
    for n in notes:
        src = f" ({n.source})" if n.source else ""
        summary = n.summary or "—"
        lines.append(f"- **{n.title}**{src}: {summary}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Wave 7B — BM25 body retrieval
# ---------------------------------------------------------------------------

class NoteExcerpt(BaseModel):
    """The full-body projection of a research note. Used for top-K
    retrieval (Wave 7B) when the agent wants more than a one-line summary
    but the corpus is too large to inject every body wholesale."""
    title: str
    source: str = ""
    body: str
    score: float = 0.0


# Hard cap on combined body bytes injected per agent run. Locked in
# MASTER_PLAN. Tighter than the summary budget because each body can run
# 2-4KB on its own; 4KB total is roughly 2-3 medium notes.
_BODY_CHAR_CAP = 4096


def _bm25_score_body(
    query_tokens: List[str], doc_tokens: List[str],
    df: Dict[str, int], n_docs: int, avgdl: float,
    k1: float = 1.5, b: float = 0.75,
) -> float:
    """Vendored BM25 — same form as `services/retrieval_service._bm25_score`
    but kept local to avoid circular imports between services. Identical
    constants so retrieval over notes scores comparably to filings."""
    import math
    from collections import Counter
    score = 0.0
    tf = Counter(doc_tokens)
    dl = len(doc_tokens) or 1
    for q in query_tokens:
        if q not in tf:
            continue
        idf = math.log(1 + (n_docs - df.get(q, 0) + 0.5) / (df.get(q, 0) + 0.5))
        f = tf[q]
        score += idf * (f * (k1 + 1)) / (f + k1 * (1 - b + b * dl / avgdl))
    return score


_BODY_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9\-]+")


def _tokenize_body(text: str) -> List[str]:
    return [t.lower() for t in _BODY_TOKEN_RE.findall(text or "")]


def select_bodies(
    agent_name: str, query: str, *,
    sector: Optional[str] = None,
    sub_industry: Optional[str] = None,
    ticker: Optional[str] = None,
    corpus_root: Optional[Path] = None,
    top_k: int = 2,
    char_cap: int = _BODY_CHAR_CAP,
    today: Optional[_date] = None,
) -> List[NoteExcerpt]:
    """Wave 7B: BM25 over note bodies, returns top-K most-relevant excerpts.

    The same routing filter that gates `select_for` runs first — bodies
    are only ranked over the agent-eligible subset. `query` is the
    agent's working context (profile + sector + cohort + regime
    rendered to a single string by the caller).

    `top_k` caps the number of notes returned; `char_cap` is a hard cap
    on combined body bytes. When the top-ranked notes would exceed
    `char_cap`, the lower-ranked ones are dropped (deterministic ordering
    on tie via title) so the prompt budget stays bounded regardless of
    corpus size.

    Returns `[]` cleanly when the filtered corpus is empty or the query
    matches no notes — caller falls through to summaries-only injection.
    """
    notes = list_notes(corpus_root=corpus_root)
    eligible: List[ResearchNote] = []
    for n in notes:
        fm = n.frontmatter
        if not _is_active(fm, today=today):
            continue
        if not _matches_filter(fm.applies_to_agents, agent_name):
            continue
        if not _matches_filter(fm.applies_to_sectors, sector):
            continue
        if not _matches_filter(
            fm.applies_to_sub_industries, sub_industry,
            empty_means_no_restriction=True,
        ):
            continue
        if not _matches_filter(
            fm.applies_to_tickers, ticker,
            empty_means_no_restriction=True,
        ):
            continue
        eligible.append(n)
    if not eligible:
        return []

    # BM25 stats over the eligible subset.
    docs = [(_tokenize_body(n.body), n) for n in eligible]
    from collections import defaultdict
    df: Dict[str, int] = defaultdict(int)
    for tokens, _ in docs:
        for t in set(tokens):
            df[t] += 1
    n_docs = len(docs)
    avgdl = sum(len(t) for t, _ in docs) / max(1, n_docs)
    q_tokens = _tokenize_body(query)

    scored: List[tuple[float, ResearchNote]] = []
    for tokens, note in docs:
        s = _bm25_score_body(q_tokens, tokens, df, n_docs, avgdl)
        if s > 0:
            scored.append((s, note))
    # Deterministic ordering: score desc, then weight desc, then title asc.
    scored.sort(
        key=lambda r: (
            -r[0], -r[1].frontmatter.weight, r[1].frontmatter.title.lower(),
        ),
    )

    out: List[NoteExcerpt] = []
    used = 0
    for score, note in scored[: max(top_k * 2, top_k)]:
        if len(out) >= top_k:
            break
        body = note.body or ""
        if used + len(body) > char_cap:
            # Truncate the last note's body if a partial fits, so cap is
            # respected exactly without a one-note-bigger-than-cap edge case.
            remaining = char_cap - used
            if remaining < 200:
                break
            body = body[:remaining].rstrip() + "…"
        out.append(NoteExcerpt(
            title=note.frontmatter.title,
            source=note.frontmatter.source,
            body=body,
            score=round(score, 3),
        ))
        used += len(body)
        if used >= char_cap:
            break
    return out


def render_body_block(excerpts: List[NoteExcerpt]) -> str:
    """Markdown block of the top-K full bodies. Empty string when no excerpts."""
    if not excerpts:
        return ""
    lines = ["## Discretionary investment context (relevant excerpts)"]
    for e in excerpts:
        src = f" ({e.source})" if e.source else ""
        lines.append(f"### {e.title}{src}")
        lines.append(e.body)
    return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Wave 7C — unified per-agent injection helper
# ---------------------------------------------------------------------------

def build_notes_block_for_agent(
    agent_name: str, profile: Optional[Dict[str, Any]] = None, *,
    extra_query: str = "",
    max_summaries: int = 6,
    top_k_bodies: int = 2,
    body_char_cap: int = _BODY_CHAR_CAP,
    today: Optional[_date] = None,
) -> str:
    """Wave 7C: one-call entry point for any specialist agent.

    Combines summary-only injection (Wave 7A) with BM25 top-K body
    retrieval (Wave 7B) into a single markdown block ready to splice
    into the agent's prompt. Returns the empty string when nothing
    matches the routing filter — callers can unconditionally
    concatenate the result.

    `profile` is the same company-profile dict the agents already pass
    around; we pull `sector`, `sub_industry`, `ticker`, `drivers`,
    `risks` out of it to feed both routing and the BM25 query.
    `extra_query` lets the caller add agent-specific keywords (e.g.,
    "DCF terminal_growth" for the valuation agent) so retrieval lands
    on the right notes when corpus distribution is uneven.

    The same defensive wrapper pattern as the sector agent: this
    function should never raise — exceptions become an empty string
    + a debug log.
    """
    profile = profile or {}
    sector = profile.get("sector") or None
    sub_industry = profile.get("sub_industry") or profile.get("industry") or None
    ticker = profile.get("ticker") or None
    try:
        summaries = select_for(
            agent_name, sector=sector, sub_industry=sub_industry, ticker=ticker,
            max_notes=max_summaries, today=today,
        )
        bm25_query_parts = [
            sector or "", sub_industry or "", ticker or "",
            profile.get("company_name", ""),
            " ".join(profile.get("drivers") or []),
            " ".join(profile.get("risks") or []),
            extra_query,
        ]
        bm25_query = " ".join(p for p in bm25_query_parts if p)
        excerpts = select_bodies(
            agent_name, bm25_query, sector=sector, sub_industry=sub_industry,
            ticker=ticker, top_k=top_k_bodies, char_cap=body_char_cap,
            today=today,
        )
        blocks = [
            render_summary_block(summaries),
            render_body_block(excerpts),
        ]
        return "\n\n".join(b for b in blocks if b)
    except Exception as exc:  # pragma: no cover — research notes never block a memo
        log.debug("research notes build failed for %s: %s", agent_name, exc)
        return ""
